version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  node-red:
    image: nodered/node-red:latest
    restart: always
    container_name: node-red
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    restart: always
    ports:
      - 3000:3000
    user: '104'
  Python:
    image: bonos2
    container_name: bonos_python
  Python1:  
    image: high
    container_name: python_highchart
    ports: 
     -  5000:5000
  
